version: '3.1'
services:
  dbpostgresql:
    image: postgres
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  demo-app:
    container_name: demo-app-springboot-postgresql-container
    image: demo-app-springboot-postgresql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
volumes:
  postgres-data: